src/Entity/Zamowienie.php
<?php

namespace App\Entity;

use App\Repository\ZamowienieRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ZamowienieRepository::class)
 */
class Zamowienie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numer_trackingowy;

    /**
     * @ORM\Column(type="integer")
     */
    private $nadawca;

    /**
     * @ORM\Column(type="integer")
     */
    private $odbiorca;

    /**
     * @ORM\Column(type="integer")
     */
    private $zleceniodawca;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sub_nadawca;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sub_odbiorca;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sub_zleceniodawca;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="zamowienies")
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumerTrackingowy(): ?string
    {
        return $this->numer_trackingowy;
    }

    public function setNumerTrackingowy(string $numer_trackingowy): self
    {
        $this->numer_trackingowy = $numer_trackingowy;

        return $this;
    }

    public function getNadawca(): ?int
    {
        return $this->nadawca;
    }

    public function setNadawca(int $nadawca): self
    {
        $this->nadawca = $nadawca;

        return $this;
    }

    public function getOdbiorca(): ?int
    {
        return $this->odbiorca;
    }

    public function setOdbiorca(int $odbiorca): self
    {
        $this->odbiorca = $odbiorca;

        return $this;
    }

    public function getZleceniodawca(): ?int
    {
        return $this->zleceniodawca;
    }

    public function setZleceniodawca(int $zleceniodawca): self
    {
        $this->zleceniodawca = $zleceniodawca;

        return $this;
    }

    public function getTelefon(): ?string
    {
        return $this->telefon;
    }

    public function setTelefon(string $telefon): self
    {
        $this->telefon = $telefon;

        return $this;
    }

    public function getSubNadawca(): ?bool
    {
        return $this->sub_nadawca;
    }

    public function setSubNadawca(bool $sub_nadawca): self
    {
        $this->sub_nadawca = $sub_nadawca;

        return $this;
    }

    public function getSubOdbiorca(): ?bool
    {
        return $this->sub_odbiorca;
    }

    public function setSubOdbiorca(bool $sub_odbiorca): self
    {
        $this->sub_odbiorca = $sub_odbiorca;

        return $this;
    }

    public function getSubZleceniodawca(): ?bool
    {
        return $this->sub_zleceniodawca;
    }

    public function setSubZleceniodawca(bool $sub_zleceniodawca): self
    {
        $this->sub_zleceniodawca = $sub_zleceniodawca;

        return $this;
    }

    public function getStatus(): ?status
    {
        return $this->status;
    }

    public function setStatus(?status $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ZamowienieType.php
<?php

namespace App\Form;

use App\Entity\Zamowienie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class ZamowienieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numer_trackingowy', TextType::class,
            ['constraints' => [
                new Regex('/[G][K][0-9]{9}/')
            ]])
            ->add('nadawca')
            ->add('odbiorca')
            ->add('zleceniodawca')
            ->add('telefon', TextType::class,
            ['constraints' => [
                new Regex('/^\+?[0-9]{2}([0-9]{7}|[0-9]{9})$/i')
            ]])
            ->add('sub_nadawca')
            ->add('sub_odbiorca')
            ->add('sub_zleceniodawca')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Zamowienie::class,
        ]);
    }
}

src/Controller/ZamowienieController.php
<?php

namespace App\Controller;

use App\Entity\Zamowienie;
use App\Form\ZamowienieType;
use App\Form\Zamowienie2Type;
use App\Repository\ZamowienieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Doctrine\Persistence\ManagerRegistry;


/**
 * @Route("/zamowienie")
 */
class ZamowienieController extends AbstractController
{
    /**
     * @Route("/", name="app_zamowienie_index", methods={"GET"})
     */
    public function index(ZamowienieRepository $zamowienieRepository): Response
    {
        $zamowienie = new Zamowienie();
        $form = $this->createForm(Zamowienie2Type::class, $zamowienie);

        return $this->render('zamowienie/index.html.twig', [
            'zamowienies' => $zamowienieRepository->findAll(),
            'form' => $form->createView()
        ]);
    }

       
    /**
     * @Route("/search", name="app_zamowienie_search")
     */
    public function search(ZamowienieRepository $zamowienieRepository, Request $request): Response
    {
            $zam = $zamowienieRepository->findByNumerAndStatus($request->get('numer'), $request->get('status')); 
            
            return new Response(json_encode($zam != null? $zam->getId() : 0));
    }   

    /**
     * @Route("/new", name="app_zamowienie_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ZamowienieRepository $zamowienieRepository): Response
    {
        $zamowienie = new Zamowienie();
        $form = $this->createForm(ZamowienieType::class, $zamowienie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $zamowienieRepository->add($zamowienie);
            return $this->redirectToRoute('app_zamowienie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('zamowienie/new.html.twig', [
            'zamowienie' => $zamowienie,
            'form' => $form
        ]);
    }

    /**
     * @Route("/{id}", name="app_zamowienie_show", methods={"GET"})
     */
    public function show(Zamowienie $zamowienie): Response
    {
        return $this->render('zamowienie/show.html.twig', [
            'zamowienie' => $zamowienie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_zamowienie_edit", methods={"GET", "POST"})
     */
    public function edit(ManagerRegistry $doctrine, Request $request, Zamowienie $zamowienie, ZamowienieRepository $zamowienieRepository, HttpClientInterface $client): Response
    {
        $zam = $zamowienieRepository->findOneById($zamowienie->getId());
        $entityManager = $doctrine->getManager();
        $zam = $entityManager->getUnitOfWork()->getOriginalEntityData($zamowienie);
        $form = $this->createForm(ZamowienieType::class, $zamowienie);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            if ($zam['status_id'] != $zamowienie->getStatus()->getId() 
              &&   ($zamowienie->getSubNadawca() || $zamowienie->getSubOdbiorca() || $zamowienie->getSubZleceniodawca())) {
                /*$response = $this->client->request(
                    'GET',
                    'powiadomienie klientow'
                );*/
                $this->addFlash('success', 'Powiadomiono klienta!');
            } else {
                $this->addFlash('success',  'Bez powiadomiwnia!');

            }
        
            $zamowienieRepository->add($zamowienie);

            return $this->redirectToRoute('app_zamowienie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('zamowienie/edit.html.twig', [
            'zamowienie' => $zamowienie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_zamowienie_delete", methods={"POST"})
     */
    public function delete(Request $request, Zamowienie $zamowienie, ZamowienieRepository $zamowienieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$zamowienie->getId(), $request->request->get('_token'))) {
            $zamowienieRepository->remove($zamowienie);
        }

        return $this->redirectToRoute('app_zamowienie_index', [], Response::HTTP_SEE_OTHER);
    }

 
}

templates/zamowienie/_delete_form.html.twig
<form method="post" action="{{ path('app_zamowienie_delete', {'id': zamowienie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ zamowienie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/zamowienie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/zamowienie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Zamowienie{% endblock %}

{% block body %}
    <h1>Edit Zamowienie</h1>

    {{ include('zamowienie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_zamowienie_index') }}">back to list</a>

    {{ include('zamowienie/_delete_form.html.twig') }}
{% endblock %}

templates/zamowienie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zamowienie index{% endblock %}

{% block body %}
    <h1>Wyszukiwarka</h1>

    {{ form_start(form) }}
        {{ form_widget(form.numer_trackingowy, { 'id': 'numer' }) }}
        {{ form_widget(form.status, { 'id': 'status' }) }}
        <button type="button" class="btn" id="show">show</button>
        <button type="button" class="btn" id="edit">edit</button>
    {{ form_end(form) }}
    </br>
    <h1>Zamowienie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numer_trackingowy</th>
                <th>Nadawca</th>
                <th>Odbiorca</th>
                <th>Zleceniodawca</th>
                <th>Telefon</th>
                <th>Sub_nadawca</th>
                <th>Sub_odbiorca</th>
                <th>Sub_zleceniodawca</th>
                <th>status</status>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for zamowienie in zamowienies %}
            <tr>
                <td>{{ zamowienie.id }}</td>
                <td>{{ zamowienie.numerTrackingowy }}</td>
                <td>{{ zamowienie.nadawca }}</td>
                <td>{{ zamowienie.odbiorca }}</td>
                <td>{{ zamowienie.zleceniodawca }}</td>
                <td>{{ zamowienie.telefon }}</td>
                <td>{{ zamowienie.subNadawca ? 'Yes' : 'No' }}</td>
                <td>{{ zamowienie.subOdbiorca ? 'Yes' : 'No' }}</td>
                <td>{{ zamowienie.subZleceniodawca ? 'Yes' : 'No' }}</td>
                <td>{{ zamowienie.status.status }}</td>
                <td>
                    <a href="{{ path('app_zamowienie_show', {'id': zamowienie.id}) }}">show</a>
                    <a href="{{ path('app_zamowienie_edit', {'id': zamowienie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_zamowienie_new') }}">Create new</a>

    <script>
        $( document ).ready(function() {
            $(document).on('click', '#show', function() {
                 $.ajax({
                    method: "POST",
                    url: "{{ path('app_zamowienie_search') }}", 
                    data: { numer: $('#numer').val(), status: $('#status').val() }
                })
                .done(function( result ) {
                        let location = "{{ path('app_zamowienie_show', {'id': 'r'}) }}";
                        if (result != '0') {
                            window.location.href = location.replace('r', result) 
                        }
                });  
             });
            $(document).on('click', '#edit', function() {
                 $.ajax({
                    method: "POST",
                    url: "{{ path('app_zamowienie_search') }}", 
                    data: { numer: $('#numer').val(), status: $('#status').val() }
                })
                .done(function( result ) {
                        let location = "{{ path('app_zamowienie_edit', {'id': 'r'}) }}";
                        if (result != '0') {
                            window.location.href = location.replace('r', result) 

                            console.log(location.replace('r', result) )
                        }
                });  
             });

    
        });
    </script>
{% endblock %}

templates/zamowienie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Zamowienie{% endblock %}

{% block body %}
    <h1>Create new Zamowienie</h1>
    {{ include('zamowienie/_form.html.twig') }}


    <a href="{{ path('app_zamowienie_index') }}">back to list</a>
{% endblock %}

templates/zamowienie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Zamowienie{% endblock %}

{% block body %}
    <h1>Zamowienie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ zamowienie.id }}</td>
            </tr>
            <tr>
                <th>Numer_trackingowy</th>
                <td>{{ zamowienie.numerTrackingowy }}</td>
            </tr>
            <tr>
                <th>Nadawca</th>
                <td>{{ zamowienie.nadawca }}</td>
            </tr>
            <tr>
                <th>Odbiorca</th>
                <td>{{ zamowienie.odbiorca }}</td>
            </tr>
            <tr>
                <th>Zleceniodawca</th>
                <td>{{ zamowienie.zleceniodawca }}</td>
            </tr>
            <tr>
                <th>Telefon</th>
                <td>{{ zamowienie.telefon }}</td>
            </tr>
            <tr>
                <th>Sub_nadawca</th>
                <td>{{ zamowienie.subNadawca ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Sub_odbiorca</th>
                <td>{{ zamowienie.subOdbiorca ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Sub_zleceniodawca</th>
                <td>{{ zamowienie.subZleceniodawca ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>status</th>
                <td>{{ zamowienie.status.status }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('app_zamowienie_index') }}">back to list</a>

    <a href="{{ path('app_zamowienie_edit', {'id': zamowienie.id}) }}">edit</a>

    {{ include('zamowienie/_delete_form.html.twig') }}
{% endblock %}